defaults:
  - model_checkpoint
  - model_summary
  - rich_progress_bar
  - _self_
  # - early_stopping

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: global_step
  mode: "max"
  save_top_k: 10
  every_n_train_steps: 10000
  save_last: True
  auto_insert_metric_name: True
  verbose: True

# early_stopping:
#   monitor: "val/acc"
#   patience: 100
#   mode: "max"

model_summary:
  max_depth: -1
