# @package _global_

defaults:
  - _self_
  - data: vctk # choose datamodule with `test_dataloader()` for evaluation
  - model: vits2_multi
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
