# @package _global_

# uses only 0.1% of the training data and 12.5% of validation/test data

defaults:
  - default

trainer:
  max_epochs: 1
  limit_train_batches: 0.001
  limit_val_batches: 0.125
  limit_test_batches: 0.125
